sonar.projectKey=caioalbert_example-phpunit
sonar.projectName=example-phpunit

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*Test.php

sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.php.tests.reportPath=build/logs/junit.xml
sonar.sourceEncoding=UTF-8
